### ISSUE TITLE
sim.setup() error

### ISSUE THREAD

**Issue by DrakeGhaderi** [murillo-group/sarkas#55]
Hello all,

I am student using your program Sarkas with the goal of obtaining plasma viscosities. After downloading Sarkas, I used the ["Quickstart" guide](https://murillo-group.github.io/sarkas/documentation/Tutorial_NB/Quickstart.html) to make sure everything was running smoothly. I downloaded and opened the provided notebook, and changed the "input_file_name" variable to "/home/admin17/anaconda3/envs/sarkas/Testing/yukawa_mks_p3m.yaml" (the location of the input file on my computer). Everything else remained unchanged. After running the second cell, I recieved the following error:

"AttributeError: 'NoneType' object has no attribute 'lower'"

I have also attatched a PDF of my notebook for more details on the error.
[Quickstart_error.pdf](https://github.com/murillo-group/sarkas/files/10209318/Quickstart_error.pdf)

Has anybody encountered this bug before and know how to solve it? Any help would be appreciated.

Thank you,
Drake Ghaderi

**Comment by SilvestriStefano** [comment]
Hello @DrakeGhaderi ,
thank you for your question.

It seems that the [`yocp_quickstart.yml`](https://github.com/murillo-group/sarkas/blob/master/docs/examples/YOCP/input_files/yocp_quickstart.yaml) is missing the `Thermostat` section that is why you are getting the error. Try using the [`yocp_viscosity.yaml`](https://github.com/murillo-group/sarkas/blob/master/docs/examples/YOCP/input_files/yocp_cgs_pp.yaml)template.

**Comment by DrakeGhaderi** [comment]
Thank you very much sir, your solution worked.
